server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   # mybatis 配置文件所在位置
  type-aliases-package: com.zhao.springcloud.entry     #所有entry别名 的类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                  #mapper 映射文件
spring:
  profiles: dev
  application:
    name: microservicecloud-dept                       # 注册到eureka服务中心的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       #数据源
    driver-class-name: com.mysql.jdbc.Driver           #mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                      # 数据库连接池的最小维持数
      initial-size: 5                                  # 初始化连接数
      max-total: 10                                    # 最大连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间
eureka:
  client:  # 客户端注册进 eureka服务列表
    service-url:
     defaultZone: http://localhost:7001/eureka
     # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: microservicecloud-dept  # 自定义服务名称信息
    prefer-ip-address: true  # 访问路径可以显示ip地址
info: 
  app.name: pr
  company.name: www.pr.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$